### ISSUE TITLE
Usage: ActionController::Parameters must be converted to expected input

### ISSUE THREAD

**Issue by bf4** [DmitryTsepelev/store_model#101]
I don't see any documentation about this, but I was surprised to see a

`failed casting <ActionController::Parameters {...} permitted: false>, only String, Hash or <model>  instances are allowed`

Thought it's probably right design and should be documented.

**Comment by DmitryTsepelev** [comment]
Hi @bf4!

It's documented in somewhere Rails itself—they say that `ActionController::Parameters` is not even an ancestor of hash, so we have to perform `to_h` by hand. Anyway, I'd be happy to merge any documentation improvements 🙂

**Comment by bf4** [comment]
Thanks.  Just thought it would a nice gotcha to point out.   I'll make a PR

**Comment by bf4** [comment]
Similarly, in terms of how Rails handles mutations to objects, any changes to models once built don't mark the attribute (we're using an array type) as changed, and don't get casted back on save.  I'm looking to see the best practice here.  probably something like below

```ruby
attribute :my_stored_models, MyStoredModel.to_array_type

def my_stored_models=(collection)
  super.each(&:set_derived_attributes)
end

after_validation do
  next if errors[:my_stored_models].any?
  # some attributes of the stored models are derived, so reassign to ensure the stored_model has the same data as the instances
  self.my_stored_models = my_stored_models.map(&:as_json)
end
```

I'll make a new issue once I have something clear to suggest

**Comment by bf4** [comment]
Yeah, I'm behind on creating my PR :)

**Comment by DmitryTsepelev** [comment]
haha let's open it back

**Comment by bf4** [comment]
Made a quickee PR. have at it
