### ISSUE TITLE
Presence validation fails if value is false

### ISSUE THREAD

**Issue by chrise86** [DmitryTsepelev/store_model#107]
I have boolean attributes defined as follows:

```
class NotificationSettings
  include StoreModel::Model

  attribute :launched, :boolean, default: true

  validates :launched, presence: true
end
```

If the value is changed to `false` the presence validation fails.

**Comment by DmitryTsepelev** [comment]
Check this out https://stackoverflow.com/questions/27002946/rails-validates-presense-not-validating-on-boolean — TLDR 
```
irb(main):001:0> false.present?
=> false
```

**Comment by chrise86** [comment]
> Check this out https://stackoverflow.com/questions/27002946/rails-validates-presense-not-validating-on-boolean — TLDR
> 
> ```
> irb(main):001:0> false.present?
> => false
> ```

Ah of course... I'm tired... 🤦
