### ISSUE TITLE
Delegation of `fetch` to `attributes` causes issues

### ISSUE THREAD

**Issue by danielvdao** [DmitryTsepelev/store_model#129]
### Context

When using `fetch` on the model - the model can result in unexpected responses. Take for example:

```ruby
class Configuration
  include StoreModel::Model

  attribute :id
end

example = Configuration.new
puts example.id # nil
puts example.fetch(:id) # KeyError: key not found: :id
```

I have a PR here: https://github.com/DmitryTsepelev/store_model/pull/128 to continue the discussion! 🙏🏽

**Comment by danielvdao** [comment]
Hey @DmitryTsepelev would it make sense to close this issue? I'm not sure what to do, and I assume maybe you're busy and haven't kept up with the PR or think the current way `fetch` works makes sense. Let me know 👍🏽

**Comment by DmitryTsepelev** [comment]
Sounds good, will close for now 🙂
