### ISSUE TITLE
accepts_nested_attributes_for allow partial updates

### ISSUE THREAD

**Issue by acetinick** [DmitryTsepelev/store_model#157]
When using accepts_nested_attributes_for on models the JSON objects gets overidden completely with the next update that happens on the model.

eg.  if you have two attributes in the store,  and update each atrtibute using two separate forms,  it will override the whole store with only the new attribute.

To fix this I have a override in my model, but feel it should be a default for the library.

![image](https://github.com/DmitryTsepelev/store_model/assets/571649/b8aa8d33-b52e-4d0d-888b-6fd44979be53)

**Comment by DmitryTsepelev** [comment]
Hey hey, good call! Wanna try to make a PR to make it work on the gem level? 🙂

**Comment by alexeevit** [comment]
Good call! At the same time, what do we indeed want to override the whole hash with the new hash, e.g. delete some of the attributes? I was thinking about an attribute `_partial` that'd be passed with the hash, so it could indicate only partial update, but I don't like interfering with the original data.

**Comment by DmitryTsepelev** [comment]
Likely gonna be addressed by #180
