### ISSUE TITLE
Parent Class using sti_class prepend the class names 

### ISSUE THREAD

**Issue by omarsancas** [DmitryTsepelev/store_model#177]
I have this Base Class with sti_class 
```ruby
Module AnonymousModule
  class AnonymousClass < ApplicationRecord
    include AnonymousModule::CommonFunctionality

    prefixed_with :anonymous

    self.table_name = 'anonymous'

    self.inheritance_column = :work_country

    sig { params(type_name: String).returns(T.class_of(AnonymousClass)) }
    def self.find_sti_class(type_name)
      case type_name      
      when AnonymousService::COLOMBIA
        AnonymousModule::ColombiaClass
      else
        AnonymousModule::AnonymousClass
      end
    rescue NameError
      super
    end
```

And I validate a column emergency_contact with StoreModel
```ruby
module Attributes
	module AnonymousClass
		class EmergencyContact
			include StoreModel::Model

			attribute :first_name, :string, default: ''
			attribute :last_name, :string, default: ''
			attribute :relationship, :string, default: ''
			attribute :phone_number, Attributes::ContactInfo::PhoneNumber.to_type

		end
	end
end
```
When the phone number is not valid the message error show 
`AnonymousClass:ColombiaClass is invalid: Emergency contact Phone number is invalid.`
 I only wants to show Emergency contact Phone number is invalid in the backend, I try to overwrite with a lamba strategy or a custom validator but only override the `Emergency contact Phone number is invalid`

**Comment by DmitryTsepelev** [comment]
Hello! What's the desired behavior you're looking for? 🙂

**Comment by omarsancas** [comment]
I have not found a way to just display `Emergency contact Phone number is invalid` because showing the parent class it's irrelevant for the end user. So I need to disable showing the parent class `AnonymousClass:ColombiaClass is invalid:` I hope to makes sense

**Comment by omarsancas** [comment]
I hope you're doing well. I wanted to follow up on the comment. I understand you might be busy

**Comment by DmitryTsepelev** [comment]
Hey hey, I was on vacation, and eventually will come back here, but things would be faster if I'd have a failing spec 🙂

**Comment by omarsancas** [comment]
I figure it out, this error is not related to store_model gem so I'm going to close this issue. Thanks for your support!
