### ISSUE TITLE
How to have an attribute of type Hash?

### ISSUE THREAD

**Issue by chernish2** [DmitryTsepelev/store_model#178]
Firstly thank you a lot for this great GEM! I have a question.
I need to have an attribute of type Hash (just usual Ruby Hash).
When I'm making
`attribute :hash_field, :hash, default: -> { {} }`
I got an error:
`ArgumentError: Unknown type :hash`
My current workaround is to define the type HashType in 
`app/types/hash_type.rb `
and then register it in 
`config/initializers/types.rb. `
May be I'm missing something? Is it for real that the Hash type is not supported out of the box?

**Comment by DmitryTsepelev** [comment]
Hey @chernish2! Unfortunately yes https://api.rubyonrails.org/classes/ActiveModel/Type.html. Maybe that will be a good addition to the Rails codebase 😉

**Comment by brentgreeff** [comment]
Slightly off topic, but this is not working for me.

```
NameError:
  uninitialized constant HashType
# ./config/initializers/types.rb:1
```

`HashType` is defined in `app/types/hash_type.rb`

For some reason zeitwerk doesnt seem to know where to look.

- Rails 8 & Ruby 3.3.

**Comment by DmitryTsepelev** [comment]
I remember there was an option for Zeitwerk to log everything it does during the initialization, I'd start there. For instance, it might break if application somehow tries to load something else from this file _before_ the Zeitwerk init stage
