### ISSUE TITLE
simple_form incompatiblity 

### ISSUE THREAD

**Issue by rainerborene** [DmitryTsepelev/store_model#24]
Now that `store_model` respond to a method named `type_for_attribute`, it is incompatible with `simple_form` gem because of these two lines as you can see [here](https://github.com/plataformatec/simple_form/search?utf8=%E2%9C%93&q=has_attribute&type=).

I had to copy and paste `has_attribute?` implementation from [
`ActiveRecord::AttributeMethods`](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/attribute_methods.rb#L236) module to make it work again with `simple_form`.

```ruby
def has_attribute?(attr_name)
  @attributes.key?(attr_name.to_s)
end
```

@DmitryTsepelev Can you include the above method on the StoreModel base class, please?

**Comment by DmitryTsepelev** [comment]
Hi @rainerborene!

Makes sense, here is a [PR](https://github.com/DmitryTsepelev/store_model/pull/25), could you please take a quick look?

**Comment by rainerborene** [comment]
@DmitryTsepelev Just tried out `has_attribute` branch. It's working now. Thank you!

**Comment by DmitryTsepelev** [comment]
Rolled out 0.5.1, let me know if something goes wrong. Thanks for the report!

**Comment by JoeKaldas** [comment]
@rainerborene Can you please share how you did it with simple form?
I'm trying to use simple form but struggling a bit
