### ISSUE TITLE
Connect store models with their parents

### ISSUE THREAD

**Issue by FunkyloverOne** [DmitryTsepelev/store_model#31]
It would be nice to have something like `#parent` method, to get store model's parent object.

I just thought it might be useful. And I would definitely appreciate it in my project :)

It seems like it might be an additional step during object initialization. _(and in more places)_

I also think it is potentially related to https://github.com/DmitryTsepelev/store_model/issues/30, as it kind of "tightens" the connection between parent and store model.

**Comment by DmitryTsepelev** [comment]
Hi @FunkyloverOne! This sounds reasonable, I'll try to make it implemented soon 🙂

**Comment by DmitryTsepelev** [comment]
@FunkyloverOne Rolled out as part of `0.6.0` with a minor [limitation](https://github.com/DmitryTsepelev/store_model/pull/35#issuecomment-531556541) for array attributes
