### ISSUE TITLE
ActiveModel::UnkownAttributeError in Rails 5.2

### ISSUE THREAD

**Issue by destructobeam** [DmitryTsepelev/store_model#37]
Hi there,

It looks like when an attribute is removed from a `StoreModel::Model` and a value exists for it in the JSON, Rails is raising an `ActiveModel::UnkownAttributeError` when deserialising from the database. This is happening to me on a nested model.

Possibly related to issue https://github.com/DmitryTsepelev/store_model/issues/22

Thanks!

**Comment by DmitryTsepelev** [comment]
Hi @destructobeam! Thanks for pointing that out, I'll try to investigate it next week

**Comment by DmitryTsepelev** [comment]
@destructobeam I've written [a spec](https://github.com/DmitryTsepelev/store_model/pull/39) for this case, and it seems to be working. Could you please review my PR and let me know what's missing or come up with a failing test? Also, please check what version you're using, `#unknown_attributes` was added in `0.5.0` and worked only with singular attributes, array support was added in `0.5.3`.

**Comment by DmitryTsepelev** [comment]
Hi @destructobeam, did you have a chance to take a look at it?

**Comment by destructobeam** [comment]
@DmitryTsepelev Not yet sorry, been pretty busy. Will be able to take a look this week or next though.

**Comment by DmitryTsepelev** [comment]
Closing the issue for now
