### ISSUE TITLE
Set to not raise_cast_error

### ISSUE THREAD

**Issue by evanshabsove** [DmitryTsepelev/store_model#51]
Hi there! First off thanks for the gem, secondly this is a feature request which I'm happy to work at. 

Our use case has a client, and this client can turn on certain customizations. If customization is turned on then all items in that client can set there own individual values for that customization. 

For example, let's say a client has the customization `foo` and `bar` turned on an item inside of that client will have a jsonb data structure of 

```
{
   foo: {
   },
  bar: {
  }
}
```

And another client only has the customization type `foobar` turned on the jsonb data for an item will look like

```
{
   foobar: {
   }
}
```

We have about maybe 40 of these customizations (and this could grow dynamically), which means that creating StoreModel class for each of the customizations is not an ideal option. I'm handling this currently by using a mix of `method_missing` and the `unknown_attributes` method in your gem

```
class Configuration
  include StoreModel::Model

  def method_missing(m, *args, &block)
    unknown_attributes[m.to_s]
  end

end
```

This works great for reading data, but the problem comes when I'm trying to update or save data. From what I can tell, b/c there are no attributes assigned to the `Configuration` class, when it tries to cast the values it just raises the `raise_cast_error(value)` and does not accept the params being passed. I want to add some sort of override which will just push whatever data I give to it and ignore the validation in the json_type file. 

Let me know if that all makes sense, and let me know if this is something you would be willing to add to the gem. I'm happy to make a PR for it.

**Comment by evanshabsove** [comment]
Hmmm on taking a second look I'm not sure my initial diagnosis was the cause of the problem...trying to figure it out now.

**Comment by DmitryTsepelev** [comment]
Hi @evanshabsove, thanks for reaching out!

If I understand the problem correctly, you want to store one or more customization (of many more) in the same JSON column. You've mentioned, that you don't want to create a class for each possible customization, but would inline syntax solve your problem? (it's easy to add):

```
class Configuration
  include StoreModel::Model

  attribute :supplier do
    attribute :title, :string
  end
end
```

instead of

```ruby
class Supplier
  include StoreModel::Model

  attribute :title, :string
end

class Configuration
  include StoreModel::Model

  attribute :supplier, Supplier.to_type
end
```

As for the part about raised error, I guess the reason is different from empty attributes (because you don't have any validations), maybe it's caused by the `method_missing` trick. I'd be happy to assist if you share more details or reproduction example.

**Comment by evanshabsove** [comment]
Sorry for my super late reply, I've had some time to be able to look back into this for our application. 

I think at the time I didn't fully understand the problem I was facing. Looking at this again I need to be able to saved unknown attributes, which is already an issue on this project. I'm going to close this issue, thanks again for your response!
