### ISSUE TITLE
to_array_type giving error with jRuby

### ISSUE THREAD

**Issue by bhuv-cogoport** [DmitryTsepelev/store_model#54]
I am getting below error while saving the object into the database having store model attribute of to_array_type

Java::JavaLang::ClassCastException (class org.jruby.RubyNil cannot be cast to class org.jruby.RubyHash (org.jruby.RubyNil and org.jruby.RubyHash are in unnamed module of loader 'bootstrap'))

**Comment by DmitryTsepelev** [comment]
Hi @bhuv-cogoport! I've never tried to use the gem with JRuby, let's try to add it to the test matrix.

**Comment by bhuv-cogoport** [comment]
Seems like it is not properly converting the store model array into Postgres array. That why the transaction is rolling back

**Comment by DmitryTsepelev** [comment]
@bhuv-cogoport I've [configured](https://github.com/DmitryTsepelev/store_model/pull/55) CI to run specs on JRuby, and my test suite seems to pass. I guess for the further investigation I'll need a spec or another example to reproduce

**Comment by bhuv-cogoport** [comment]
I managed to run it successfully by overriding "**type**" instance method of **"StoreModel::Types::ArrayType"** class. I override it as follows:

`require 'store_model'

StoreModel::Types::ArrayType.class_eval do
  
  def type
    :jsonb
  end

end`

And in my migration file, I defined my attribute as 

`jsonb :slabs`

instead of:

`jsonb :slabs, array: true, default: []`

**Comment by DmitryTsepelev** [comment]
Okay, I guess we can close the issue for now 🙂Please let me know if you face something weird
