### ISSUE TITLE
JSONB not supported?

### ISSUE THREAD

**Issue by scottbarrow** [DmitryTsepelev/store_model#57]
The documentation does not specify a serialized column type, however the opening line suggests JSONB is supported
"Imagine that you have a model Product with a **jsonb** column called configuration. This is how you likely gonna work with this column:"

However, creating a column with jsonb does no persist the serialized values, a json column does
This is with Rails 6, postgres. Are you aware of issues around jsonb?

**Comment by DmitryTsepelev** [comment]
Hi @scottbarrow! The gem is supposed to work with any JSON column types and I use it to work with JSONB. Since you've closed the issue, please let me know if you figured it out, otherwise—I'd be happy to help.

**Comment by scottbarrow** [comment]
Thanks. I rolled back the migration adding the jsonb column added a null: false and it seemed to work. I'm not sure if that was the cause or not hence me closing the issue
