### ISSUE TITLE
Custom Error Strategy

### ISSUE THREAD

**Issue by kaelumania** [DmitryTsepelev/store_model#59]
Hi, I wondered if this behavior is intentional:

```ruby
    lambda_strategy = lambda do |attribute, base_errors, _store_model_errors|
      _store_model_errors.each do |field, message|
        base_errors.add("#{attribute}.#{field}", message)
      end
    end

    validates :thing, store_model: lambda_strategy, on: :create
```

I like it. If it's intentional, I would be nice to get it documented

**Comment by DmitryTsepelev** [comment]
I feel something similar is described [here](https://github.com/DmitryTsepelev/store_model/blob/master/docs/validations.md) at the bottom, but not this exact case
