### ISSUE TITLE
Access to class constants

### ISSUE THREAD

**Issue by MaxMernikov** [DmitryTsepelev/store_model#62]
Hi!
How I can get access to class constants?
For example I have:
promo.rb
```
class Promo < ApplicationRecord
  USER_PERMISSIONS = %w[update_profile upload_receipt].freeze

  attribute :settings, PromoSettings.to_type, default: {}
end
```
and promo_settings.rb
```
class PromoSettings
  include StoreModel::Model

  attribute :user_permissions, :array_of_strings, default: []

  validates :user_permissions,
    inclusion: {
      in: ::Promo::USER_PERMISSIONS
   }
end
```

returns `uninitialized constant Promo::USER_PERMISSIONS`
Is it ok? Can you help with this? tnx

**Comment by DmitryTsepelev** [comment]
Hi @MaxMernikov, looks like something is wrong with application namespaces (maybe there is a different `Promo` namespace somewhere?). I've tried to do the following in the separate file, and looks like it works:
```ruby
class Promo
  USER_PERMISSIONS = %w[update_profile upload_receipt].freeze
end

class PromoSettings
  puts "constant is available? #{::Promo::USER_PERMISSIONS}"
end
```

Closing the issue, since it is not related to the project

**Comment by MaxMernikov** [comment]
Да спасибо, позже обнаружили что определение констант (по какой то неведомой мне причине) оказалось после определения атрибута store_model

Спасибо за быстрый ответ.
