### ISSUE TITLE
Time zone aware date and time attributes

### ISSUE THREAD

**Issue by f-mer** [DmitryTsepelev/store_model#67]
ActiveRecord decorates `:datetime`  and `:time` attributes with a `TimeZoneConverter` type.
This ensures the time is converted automatically into the current `Time.zone`.

I'm currently working around this issue by explicitly decorating the type.

```rb
class Todo
  include StoreModel::Model

  attribute :due_at, ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter.new(ActiveModel::Type::Time.new)
end
```

Any thoughts on if it is desirable to have the same behaviour as ActiveRecord for dates and times?
This could be also made configurable through something like `StoreModel.config.time_zone_aware_attributes = true` and `StoreModel.config.time_zone_aware_types = [:datetime, :time]`.

**Comment by DmitryTsepelev** [comment]
Hi @f-mer! I think that's a helpful addition. What if we just define custom types ([docs](https://github.com/DmitryTsepelev/store_model/blob/master/docs/defining_custom_types.md)), register them and let user to use `:datetime_with_timezone` and `:time_with_timezone` (e.g., `attribute :due_at, :time_with_timezone`)? This requires no extra configuration on the application side and totally backward compatible.

**Comment by f-mer** [comment]
Hi @DmitryTsepelev, I see it is actually a direct mapping to `ActiveModel::Type`s. And ActiveModel concerns itself not with converting timezones, that totally makes sense. 

I'm not sure if this should be added to the gem because `TimeZoneConverter` is actually marked as `:nodoc:` :see_no_evil: 
Defining a custom type is a great suggestion and for now I put this code into an initializer:

`config/initializers/active_model_types.rb`
```rb
ActiveModel::Type.register(:time_with_timezone) {
  ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter.new(ActiveModel::Type::Time.new)
}
```

Thank you!
