### ISSUE TITLE
Lacking info on README

### ISSUE THREAD

**Issue by rainerborene** [DmitryTsepelev/store_model#7]
@DmitryTsepelev Can you share how you're using this gem on the frontend layer (meaning controller params and form views)? I'm facing some issues with `assign_attributes` overriding the entire hash. If possible, provide more information about these issues on the README file.

**Comment by DmitryTsepelev** [comment]
Hi @rainerborene!

Thank you for the interest, give me a couple of days to try it with plain old Rails views - we're using this gem with the React client and pass all the attributes explicitly (which I assumes works as a workaround for your issue, but I believe we can fix `assign_attributes` too)

**Comment by rainerborene** [comment]
Hey @DmitryTsepelev. Thank you! One way would be to monkey patch `assign_attributes` to mimic the behavior of `accepts_nested_attributes_for`, or the gem could support the latter by treating like a normal association (not sure about that). I'll try to split params into multiple methods like `data_params` and `post_params`, and assign each one individually.

**Comment by DmitryTsepelev** [comment]
@rainerborene I've tried to create the classical Rails app with forms, and it feels like `attribute` works like the association (the only diff is that I had to add a value to `<%= configuration_form.text_field :color, value: product.configuration.color %>`), but it's not the association, it's just a hash :) I'm going to put it into the docs, the easiest workaround I see here is to add hidden field for each field that not used on the form (in other words - the form should send the whole hash always). Please let me know if this workaround solves your issue

**Comment by rainerborene** [comment]
@DmitryTsepelev I've decided to steal your proposed solution on this unmerged pull request #8, and adapted it without extending ActiveRecord.

```ruby
# app/models/user.rb
def data=(value)
  super data.as_json.merge(value)
end
```

Now one more extra piece of code for cleaning up nil values from `data` column.
```ruby
# app/models/data.rb
class Data
  include StoreModel::Model

  # ...

  def as_json(options = nil)
    super.compact
  end
end
```

It's working like a charm!

**Comment by DmitryTsepelev** [comment]
Yeah that's definitely an option. I decided to not patch base class because I was not sure if it won't break anything. In your case it looks pretty safe
