### ISSUE TITLE
Support for ActiveRecord without Rails

### ISSUE THREAD

**Issue by masterT** [DmitryTsepelev/store_model#71]
It would be nice to be able to use this gem with ActiveRecord without having a Rails application.

**Comment by DmitryTsepelev** [comment]
Hi @masterT! The gem [depends](https://github.com/DmitryTsepelev/store_model/blob/master/store_model.gemspec#L21) on ActiveRecord only. I guess the only thing you need to do to make gem work outside of Rails is to apply the same patches that are normally performed by [railtie](https://github.com/DmitryTsepelev/store_model/blob/010c5973467fa6f3b0e8d02ea0ea9e651d2a00b9/lib/store_model/railtie.rb#L10) as part of initialisation.
