### ISSUE TITLE
Defaults are not set on new attributes

### ISSUE THREAD

**Issue by andresespinosapc** [DmitryTsepelev/store_model#73]
When I create a new attribute that has a default and validates its presence, when I save my model I get `Validation failed: <attribute> cannot be blank`. It should set the attribute to its default value

```ruby
attribute :syncing, :boolean, default: false
validates :syncing, presence: true
```

**Comment by DmitryTsepelev** [comment]
Hi @andresespinosapc! The problem is that `presence` validation uses `blank?` method, and `false.blank?` returns true. [Rails Guide](https://guides.rubyonrails.org/active_record_validations.html#presence) suggests rewriting this part to 

```ruby

validates :boolean_field_name, inclusion: { in: [true, false] }
validates :boolean_field_name, exclusion: { in: [nil] }
--



```

**Comment by andresespinosapc** [comment]
My bad, thanks!
