### ISSUE TITLE
Custom validations

### ISSUE THREAD

**Issue by JoeKaldas** [DmitryTsepelev/store_model#76]
Hello, I have a a json column called data as follow. It has name, email, description.
How can I custom validate the email for example?
I'm successful with validating using presence, format and other validations

But how can I use a custom validator? So I want to validate the email using a 3rd party gem.

Something like this:

`address = ValidEmail2::Address.new(value)`
`errors.add(key.to_s, "isn't a valid email") unless address.valid?`

How can I access the value of this attribute and the errors?

Also, is it possible to pass a parameter to the configuration?

Thank you

**Comment by DmitryTsepelev** [comment]
Hi @JoeKaldas! The gem uses validations provided by Rails, so I'd start with this [guide](https://guides.rubyonrails.org/active_record_validations.html#custom-validators). In short, you have two options: use the validator provided by the external gem (if it exists) or just write you own and call the library code:

```
class EmailValidator < ActiveModel::Validator
  def validate(record)
    address = ValidEmail2::Address.new(record.email)
    record.errors.add(key.to_s, "isn't a valid email") unless address.valid?
  end
end

class Contact
  include StoreModel::Model
  attribute :email, :string
  validates_with EmailValidator
end
```

**Comment by JoeKaldas** [comment]
Thank you so much. This is exactly what I needed. I used `ActiveModel::EachValidator` instead since I needed the attribute being validated in my case.
