### ISSUE TITLE
Predicate method for boolean

### ISSUE THREAD

**Issue by StanisLove** [DmitryTsepelev/store_model#89]
Hi! Why is a predicate method not defined for boolean attributes?
Are there any obstacles here?

```ruby
class Settings
  include StoreModel::Model

  attribute :something_enabled, :boolean, default: false
end

record.settings.something_enabled? #=> undefined method ((
```

**Comment by DmitryTsepelev** [comment]
I guess you want to mimic the default Rails behavior when each bool field has a corresponding `...?` method. We use [Attribute API](https://api.rubyonrails.org/v6.1.0/classes/ActiveRecord/Attributes/ClassMethods.html) to define attributes, and for some reason it does not define that method. So there are two _obstacles_: it does not work out of the box and no one implemented it on the gem's size 🙂

**Comment by DmitryTsepelev** [comment]
Cloesd via #97
