### ISSUE TITLE
Allow_nil: true not working

### ISSUE THREAD

**Issue by majksner** [DmitryTsepelev/store_model#9]
Hi @DmitryTsepelev,

Thanks for the gem! It seems `allow_nil: true` not working, when I try to save model with json attributes set to nil it raises

```ruby
raise StoreModel::Types::CastError,
                "failed casting #{value.inspect}, only String or Array instances are allowed"
```
or
```ruby
raise StoreModel::Types::CastError,
                "failed casting #{value.inspect}, only String, " \
                "Hash or #{@model_klass.name} instances are allowed"
```

If I add

```ruby
when nil then value
```

in both array_type.rb and json_type.rb everything works fine.

**Comment by DmitryTsepelev** [comment]
🤦‍♂ I guess I know where it comes from - investigating

**Comment by majksner** [comment]
```
[27] pry(main)> machine = Machine.new(project_id: 1, configuration: nil, rotating_elements: nil)
=> #<Machine:0x00007fdeae95dfc8
 id: nil,
 project_id: 1,
 configuration: nil>
[28] pry(main)> machine.save!
   (0.3ms)  BEGIN
   (0.3ms)  ROLLBACK
StoreModel::Types::CastError: failed casting nil, only String, Hash or MachineConfig instances are allowed
from /Users/test/.rvm/gems/ruby-2.6.3/gems/store_model-0.3.0/lib/store_model/types/json_type.rb:22:in `cast_value'
```

**Comment by DmitryTsepelev** [comment]
@majksner Thank you for catching this! Just released 0.3.1 with the [fix](https://github.com/DmitryTsepelev/store_model/pull/10) according to your suggestion

**Comment by majksner** [comment]
You're welcome, I could still see one problem and that is we don't check if allow_nil: true is set anywhere in the code.

**Comment by DmitryTsepelev** [comment]
In this case we use a regular ActiveRecord validation, and `allow_nil` [is shipped](https://edgeguides.rubyonrails.org/active_record_validations.html#allow-nil) out of the box

**Comment by majksner** [comment]
👍🏻 Thanks for the such a quick fix!
